services:
  - type: web
    name: student-predictor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /health
